### ISSUE TITLE
Review: Great Contribution

### ISSUE THREAD

**Issue by dbkeator** [Brainhack-Proceedings-2015/Oconnor_HBM_INDICloud#3]
This project provides a service to the wider research community by increasing data availability and ease of use in the Amazon cloud.  Each of the data sets they selected to import into a public S3 bucket are well-known and broadly used within the community.  The report is well written.  

It would be a good addition to the abstract to include some information on how a reader would access the bucket containing the described data sets.  Without this information the reader is left to find it on their own which is probably a needless barrier to use.  

Fix Reference: GigaScience Repository REFXXX

**Comment by nicholsn** [comment]
@DaveOC90 Have you had a chance to address the reviewer's concerns?

**Comment by DaveOC90** [comment]
Dear Reviewer,

Thank you for the kind words and suggestions. I have added detail on how to access the datasets described, and have given a specific example. With regard to the reference being incorrect, a GigaScience Repository reference has not yet been assigned but will be in the future. As such the authors wish to include it in the current manuscript as a bookmark. 

Regards,

Dave
